version: '3'

services:
    mongodb:
        image: mongo:3.6
        container_name: mongodb-estatcamp-express
        environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=example

    estatcamp:
        build: .
        restart: unless-stopped
        container_name: estatcamp-express
        ports:
            - "80:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_BASICAUTH_USERNAME=estatcamp
            - ME_CONFIG_BASICAUTH_PASSWORD=estatcamp
            - ME_CONFIG_OPTIONS_NO_DELETE=true
            - ME_CONFIG_OPTIONS_READONLY=true
        depends_on:
            - mongodb